phpmyadmin:
  image: efynox/apache2-php
  command: apache2ctl -D FOREGROUND
  links:
    - db
  ports:
    - "80:80"
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: test
  ports:
    - "3306:3306"
