<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.9 setup script
 * Date: Sun, 22 Feb 2015 18:10:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: db [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'db';
$cfg['Servers'][$i]['host'] = 'db';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '54ea1aa13cbf27.26089611';
$cfg['DefaultLang'] = 'fr';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>